version: '3'

services:
  postgres:
    build: ./database
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgres

  gql-server:
    build: ./gql-server
    container_name: gql-server
    volumes:
      - ../:/var
    external_links:
      - postgres
    ports:
      - '4000:4000'

volumes:
  data:
